### ISSUE TITLE
Cocobolo Wood

### ISSUE THREAD

**Issue by NightwolfBlue** [Forecaster/RailcraftPatronServerIssues#87] opened 2018-07-12 08:19 UTC
Cocobolo Wood from Forestry can not be cut in the Block cutting machine.

**Comment by NightwolfBlue** [comment] 2018-07-12 08:34
I did some checking.
forestry:logs.0 and forestry:logs.1 and there fireproof version can be cut, but forestry:logs.2-7 can not. Also Natura Redwood and Bloodwood.

I hope this helps.

**Comment by Generalcamo** [comment] 2018-07-22 06:36
Duplicate of #13

**Closed as completed** 2018-07-22 06:36 UTC
Labels: duplicate
