### ISSUE TITLE
Unable to make combustion potion

### ISSUE THREAD

**Issue by liach** [Forecaster/RailcraftPatronServerIssues#48] opened 2017-06-11 05:39 UTC
Combustion potion from Potion Core are made by fire charge + awkward potion on brewing stands, which conflicts with ToughAsNails heat resistance potion. Currently the combustion one is overridden by the heat resistance one. Combustion potion can derive into many types of potions, such as explosive, burst potion, etc.

**Comment by CovertJaguar** [comment] 2017-06-11 20:26
Duplicate of #17

**Comment by liach** [comment] 2017-06-11 20:31
Wait a bit they are not the same

**Comment by liach** [comment] 2017-06-12 09:03
So @CovertJaguar It will be creeper gland + awkward potion, right?

**Comment by CovertJaguar** [comment] 2017-06-13 01:59
Unless you think something like sulfur would be better?

**Comment by liach** [comment] 2017-06-13 02:01
Yes. Creeper gland should really make explosion potions (it is currently mixture from combustion potion and some others)

**Comment by liach** [comment] 2017-06-14 07:24
Let's just use creeper glands.

**Closed as completed** 2017-06-23 02:59 UTC
Labels: bug, config
